#!/bin/bash
# vim: set ft=sh:
#
# Allow an app through gatekeeper and notarization

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]:-$0}" )" >/dev/null && pwd -P)"

if [[ "$(id -u)" -ne "0" ]]; then
  echo "> Changing to root"
  exec sudo -p "> Enter SUDO password:" -E -u "root" "$SCRIPT_DIR/allow-gatekeeper" "$@"
fi

echo "> Allowing '$1' in gatekeepr and notarization" 
spctl --add "$1"
xattr -r -d com.apple.quarantine "$1"
