#!/usr/bin/env zsh
# vim: set ft=sh:
set -e

[[ -e "/opt/homebrew/bin" ]] && HOMEBREW_PREFIX="/opt/homebrew" || HOMEBREW_PREFIX="/usr/local"

if [[ -n $AWS_VAULT ]] || [[ -n $VIMRUNTIME ]]; then
  exec "$HOMEBREW_PREFIX/bin/aws" "$@"
fi

if [[ -z $AWS_PROFILE ]]; then
  exec "$HOMEBREW_PREFIX/bin/aws" "$@"
fi

exec aws-vault exec "$AWS_PROFILE" -- "$HOMEBREW_PREFIX/bin/aws" "$@"
