#!/usr/bin/env sh
set -e
BIN="$1"
shift

if [[ -n $AWS_VAULT ]] || [[ -n $VIMRUNTIME ]]; then
  exec "$BIN" "$@"
fi

if [[ -z $AWS_VAULT_PROFILE ]] && [[ -z $AWS_PROFILE ]]; then
  echo "Please set AWS_VAULT_PROFILE to your profile name" && exit 1
fi

exec aws-vault exec "${AWS_VAULT_PROFILE:-$AWS_PROFILE}" -- "${BIN}" "$@"
