#!/bin/bash
# vim: ft=sh
#
# Select and tail a cloudwatch logfile
command -v fzf >/dev/null 2>&1 || (echo "Needs 'fzf'" && exit 1)

group_name=${1:-}
timeline=${2:1h}
[ -z "${group_name}" ] && echo "Please specify a search pattern as first parameter" && exit 1

groups=$(aws logs describe-log-groups --query 'logGroups[*].logGroupName' --output text | tr "\t" "\n")
number_of_groups=$(echo "${groups}" | wc -l | tr -d ' ')

if [[ "$number_of_groups" == "0" ]]; then
	echo "Could not find a group containing string '${group_name}'" && exit 1
fi

if [[ "$number_of_groups" -gt "1" ]]; then
	echo "Too many group containing string '${group_name}'. Select one."
	groups=$(echo -n "$groups" | fzf -1 -q "$group_name")
fi

echo "Fetching '$groups' (Since: $timeline)"
aws logs tail "$groups" --since "$timeline"
