#!/usr/bin/env zsh
#
# Generates aws-vault wrapped binstubs
#
set -e
script_dir=$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" &>/dev/null && pwd -P)

declare -a BINS=(
  aws 
  packer
  terraform
)

for bin in $BINS; do
  bin_upper=$(echo $bin | tr '[:lower:]' '[:upper:]')

  echo "Generating wrapped binary '$bin'"
  cat <<-EOF > $script_dir/$bin
#!/usr/bin/env zsh
# vim: set ft=sh:
#
# This is generated by "aws-vault-generate.sh"
#
set -e

BIN="\${AWS_${bin_upper}_BIN_OVERRIDE:-$bin}"

[[ -e "/opt/homebrew/bin" ]] && HOMEBREW_PREFIX="/opt/homebrew" || HOMEBREW_PREFIX="/usr/local"

if [[ -n \$AWS_VAULT ]] || [[ -n \$VIMRUNTIME ]]; then
  exec "\$HOMEBREW_PREFIX/bin/\$BIN" "\$@"
fi

# If AWS_PROFILE is empty or "localstack" or we want to use localstack via --profile=localstack use the original aws binary
if [[ -z $AWS_PROFILE ]] || [[ "$*" == *"localstack"* ]] || [[ "${AWS_PROFILE}" == *"localstack"* ]]; then
  exec "\$HOMEBREW_PREFIX/bin/\$BIN" "\$@"
fi

exec aws-vault exec --duration 1h "\$AWS_PROFILE" -- "\$HOMEBREW_PREFIX/bin/\$BIN" "\$@"
EOF
done
