#!/usr/bin/env bash
# vim: set ft=sh:
# Replaces https://github.com/localstack/awscli-local
unset AWS_PROFILE
export AWS_ACCESS_KEY_ID=test
export AWS_SECRET_ACCESS_KEY=test
export AWS_DEFAULT_REGION="${DEFAULT_REGION:-$AWS_DEFAULT_REGION}"
/opt/homebrew/bin/aws --endpoint-url="http://${LOCALSTACK_HOST:-localhost}:4566" "$@"
