#!/bin/bash
#
# Installs an old version of a homebrew formula
# This is made extremly difficult by homebrew:

set -euo pipefail

if [[ $# -ne 2 ]]; then
  echo "Usage:"
  echo "======"
  echo "${BASH_SOURCE[0]} <formula name> <version>"
  exit 1
fi

FORMULA="$1"
VERSION="$2"
TAP="$(id -F)/$FORMULA"

brew tap-new --no-git "$TAP"
brew tap "$TAP"
brew extract --version "$VERSION" "$FORMULA" "$TAP"
brew install "$FORMULA@$VERSION"
