#!/bin/sh
#
# You must grant Accessibility permissions to both Script Editor and iTerm in:
# System Settings > Privacy & Security > Accessibility
#
osascript 2>/dev/null <<EOF
tell application "iTerm"
  -- new window
	set newWindow to (create window with profile "Default" command "${@}")

  -- move new window to the top left
  tell application "System Events"
    tell process "iTerm2"
      set position of front window to {0, 22}
    end tell
  end tell

  -- resize window
	tell newWindow
		tell current session
			set columns to 500
			set rows to 200
		end tell
	end tell
end tell

delay 0.1 

tell application "System Events"
	tell application process "iTerm"
		set position of front window to {0, 22} -- move to top-left, below menu bar
	end tell
end tell
EOF
exit 0

# vim:ft=sh
