#!/bin/sh
osascript 2>/dev/null <<EOF
tell application "iTerm"
	set newWindow to (create window with profile "Default" command "${1}")
	tell newWindow
		tell current session
			set columns to 300
			set rows to 200
		end tell
	end tell
end tell
EOF
exit 0

# vim:ft=sh
