#!/usr/bin/env bash
# shellcheck disable=SC2034

set -Eeuo pipefail
trap cleanup SIGINT SIGTERM ERR EXIT

script_dir=$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" &>/dev/null && pwd -P)

usage() {
	cat <<EOF
Usage: $(basename "${BASH_SOURCE[0]}") [-h] [-v] -a authorname <directory to change>

Script description here.

Available options:

-h, --help           Print this help and exit
-v, --verbose        Show each step as it is executed
-a, --author <name>  Adds an author exif tag to each image
EOF
	exit
}

cleanup() {
	trap - SIGINT SIGTERM ERR EXIT
}

setup_colors() {
	if [[ -t 2 ]] && [[ -z "${NO_COLOR-}" ]] && [[ "${TERM-}" != "dumb" ]]; then
		NOFORMAT='\033[0m' RED='\033[0;31m' GREEN='\033[0;32m' ORANGE='\033[0;33m' BLUE='\033[0;34m' PURPLE='\033[0;35m' CYAN='\033[0;36m' YELLOW='\033[1;33m'
	else
		NOFORMAT='' RED='' GREEN='' ORANGE='' BLUE='' PURPLE='' CYAN='' YELLOW=''
	fi
}
setup_colors

msg() {
	echo >&2 -e "${1-}"
}

die() {
	local msg=$1
	local code=${2-1} # default exit status 1
	msg "${RED}$msg${NOFORMAT}"
	exit "$code"
}

require_bin() {
	for c in "$@"; do
		command -v "$c" &>/dev/null || die "'$c' command not found, please install it"
	done
}

parse_params() {
	# default values of variables set from params
	author=''

	while :; do
		case "${1-}" in
		-h | --help) usage ;;
		-v | --verbose) set -x ;;
		-a | --author)
			author="${2-}"
			shift
			;;
		-?*) die "Unknown option: $1" ;;
		*) break ;;
		esac
		shift
	done

	args=("$@")

	# check required params and arguments
	[[ ${#args[@]} -eq 0 ]] && die "Missing directory with images to sort/tag"

	return 0
}

parse_params "$@"
require_bin jhead exiftool

msg "Working with images in directory ${args[0]}"
msg "Sorted images will be in ${args[0]}/sorted"

if [[ -n "${author}" ]]; then
	msg "Adding EXIF author='${author}' to images in ${args[0]}"
	exiftool -r -overwrite_original -author="${author}" "${args[0]}"
fi

# Rename images according to exif-tag
msg "Moving images ..."
exiftool -r "-FileName<CreateDate" -d "%Y/%Y-%m-%d/%Y_%m_%d_%H_%M_%S.%%e" "${args[0]}"
