#!/usr/bin/env bash
# See http://${FRITZ_HOST}:49000/tr64desc.xml

FRITZ_HOST="192.168.1.1"
FRITZ_USER="${FRITZBOX_USER}"
FRITZ_PASSWORD="${FRITZBOX_PASSWORD}"

if [[ -z "${FRITZ_USER}" ]] || [[ -z "${FRITZ_PASSWORD}" ]]; then
	echo "Please configure FRITZBOX_USER and FRITZBOX_PASSWORD environment variables" && exit 1
fi
# --- config done ---

# send TR-064 command
send_action() {
	location="$1"
	uri="$2"
	action="$3"

	curl \
		-s \
		--insecure \
		-m 5 \
		--anyauth \
		-u "${FRITZ_USER}:${FRITZ_PASSWORD}" \
		--url "http://$FRITZ_HOST:49000${location}" \
		-H 'Content-Type: text/xml; charset="utf-8"' \
		-H "SoapAction:${uri}#${action}" \
		-d "<?xml version='1.0' encoding='utf-8'?>
      <s:Envelope xmlns:s=\"http://schemas.xmlsoap.org/soap/envelope/\" s:encodingStyle=\"http://schemas.xmlsoap.org/soap/encoding/\">
        <s:Body>
          <u:${action} xmlns:u=\"${uri}\"></u:${action}>
        </s:Body>
      </s:Envelope>" \
		-o /dev/null \
		-w "%{http_code}"
}

#send_action "/upnp/control/wanpppconn1" "urn:dslforum-org:service:WANPPPConnection:1" "GetInfo"
send_action "/upnp/control/wanipconnection1" "urn:dslforum-org:service:WANIPConnection:1" "ForceTermination"
