#!/bin/bash
# vim: set ft=sh:
#
# Cleans up local timemachine backups which
# resulting in "no free space left on device"
#
snapshots=$(tmutil listlocalsnapshotdates / | grep -v "Snapshot")

echo "===================================="
echo "Removing local timemachine snapshots"
echo "===================================="

for snapshot_date in $snapshots; do
  echo "Removing snapshot '$snapshot_date'"
  tmutil deletelocalsnapshots "$snapshot_date"
done

