#!/usr/bin/env bash
# vim: set ft=sh:
script_dir=$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" &>/dev/null && pwd -P)
here=$(pwd)

# shellcheck disable=SC1090
source ~/.zsh/config/functions

msg() {
	echo -e "${*-}" | box 33
}

cd "${script_dir}" || exit 1

#
# testssl.sh
#
mkdir -p "${script_dir}/testssl" || true
msg "Cloning testssl"
git clone --depth 1 https://github.com/testssl/testssl.sh.git "${script_dir}/testssl"
chmod +x "${script_dir}/testssl/testssl.sh"
ln -s "${script_dir}/testssl/testssl.sh" "${script_dir}/testssl.sh"
"${script_dir}/testssl.sh" --version

cd "${here}" || exit 1
