#!/bin/bash
#
# generates a useful gitconfig stub

set -e

SCRIPTNAME=`basename $0`
USERNAME=""
EMAIL=""

usage () {
  echo "Outputs a default .gitconfig"
  echo
  echo "Usage:"
  echo "------"
  echo "./$SCRIPTNAME -u real-name-to-use -e email-to-use > ~/.gitconfig"
  echo
  echo "After running this generator follow the instructions about"
  echo "setting up your github credentials: http://help.github.com/set-your-user-name-email-and-github-token/"
  echo
  echo "sets optional config for https://github.com/aanand/git-up"
  exit
}

generate () {
  echo "[user]
  name = $USERNAME
  email = $EMAIL 
[alias]
  l = log --graph --pretty=format':%C(yellow)%h%Creset %s %C(white) (%an, %ar%Creset) %Cblue%d%Creset'
  ci = commit
  st = status
  ch = checkout
  cp = cherry-pick -x
  b = branch -v
  r = remote -v
  t = tag -l
  unstage = reset HEAD
  uncommit = reset --soft HEAD^
  unpushed = !GIT_CURRENT_BRANCH=\$(git name-rev --name-only HEAD) && git log origin/\$GIT_CURRENT_BRANCH..\$GIT_CURRENT_BRANCH --oneline
  quicklog = log --pretty=format:\"%h %cr %cn %Cgreen%s%Creset\"
  rc = rebase --continue
  ra = rebase --abort
  rs = rebase --skip
  rh = reset --hard
  clone = clone --recursive
[color]
  branch = auto
  status = auto
  diff = auto
  interactive = auto
  ui = auto
[color \"diff\"]
  whitespace = red reverse
[gc]
  auto = 1000 # auto pack repo only after 1000 losose objects have been detected
[core]
  # see http://www.git-tower.com/blog/make-git-rebase-safe-on-osx/
  trustctime = false
  autocrlf = input
  excludesfile = ~/.gitignore
  editor = "vim -u NONE -N -u ~/.vimrc-commit -c 'normal A' -c 'startinsert'"
  precomposeunicode = true
[merge]
  summary=true
  tool = extMerge
[mergetool \"extMerge\"]
  cmd = ~/.zsh/modules/git-ext-wrapper/extMerge \"\$BASE\" \"\$LOCAL\" \"\$REMOTE\" \"\$MERGED\"
  trustExitCode = false
[mergetool]
  keepBackup = false
[gc]
  auto=1
[branch]
  autosetupmerge = true
[git-up \"fetch\"]
  prune = false
  all = true
[git-up \"bundler\"]
  check = true
  autoinstall = true
[push]
  default = matching
[pull]
  rebase = true
[diff]
  algorithm = patience
  tool = meld
  #external = ~/.zsh/modules/git-ext-wrapper/extDiff
[difftool]
  prompt = false
[grep]
  patternType = perl
[rerere]
  enabled = true
"
}

if [ $# -lt "2" ]; then
  usage
  exit
fi

while getopts "u:e:" option
do
  case $option in
  u)  USERNAME=$OPTARG 
      ;;
  e)  EMAIL=$OPTARG 
      ;;
  *)  usage
      exit
      ;;
  \?) usage
      exit
      ;;
  esac
done

if [[ -n "$USERNAME" && -n "$EMAIL" ]]; then
  generate
else
  usage
fi

