#!/bin/bash
#
# generates a useful gitconfig stub

set -e

SCRIPTNAME=`basename $0`
USERNAME=""
EMAIL=""

usage () {
  echo "Outputs a default .gitconfig"
  echo
  echo "Usage:"
  echo "------"
  echo "./$SCRIPTNAME -u real-name-to-use -e email-to-use > ~/.gitconfig"
  echo
  echo "After running this generator follow the instructions about"
  echo "setting up your github credentials: http://help.github.com/set-your-user-name-email-and-github-token/"
  echo
  echo "sets optional config for https://github.com/aanand/git-up"
  exit
}

generate () {
  echo "[user]
  name = $USERNAME
  email = $EMAIL 
[alias]
  ci = commit
  st = status
  ch = checkout
  cp = cherry-pick -x
  b = branch -v
  r = remote -v
  t = tag -l
  unstage = reset HEAD
  uncommit = reset --soft HEAD^
  unpushed = !GIT_CURRENT_BRANCH=\$(git name-rev --name-only HEAD) && git log origin/\$GIT_CURRENT_BRANCH..\$GIT_CURRENT_BRANCH --oneline
  quicklog = log --pretty=format:\"%h %cr %cn %Cgreen%s%Creset\"
  rc = rebase --continue
  ra = rebase --abort
  rs = rebase --skip
  rh = reset --hard
  clone = clone --recursive
[color]
  branch = auto
  status = auto
  diff = auto
  interactive = auto
  ui = auto
[color \"diff\"]
  whitespace = red reverse
[core]
  autocrlf = input
  excludesfile = ~/.gitignore
  editor = \"vim -u NONE -N -c 'startinsert'\"
  #CUSTOM SEE VIM_CONFIG: editor = \"vim -u NONE -N -u ~/.vimrc-commit\"
[merge]
  summary=true
[gc]
  auto=1
[branch]
  autosetupmerge = true
[git-up \"fetch\"]
  prune = false
[git-up \"bundler\"]
  check = true
  autoinstall = true
[push]
  default = matching
"
}

if [ $# -lt "2" ]; then
  usage
  exit
fi

while getopts "u:e:" option
do
  case $option in
  u)  USERNAME=$OPTARG 
      ;;
  e)  EMAIL=$OPTARG 
      ;;
  *)  usage
      exit
      ;;
  \?) usage
      exit
      ;;
  esac
done

if [[ -n "$USERNAME" && -n "$EMAIL" ]]; then
  generate
else
  usage
fi

