#!/bin/bash
#
# relinks all DOTTHINGS in home to the homedir
#
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

link_or_fail() {
	local file="$1"

	name_only=${file/home\//}

	if [ -e "${HOME}/${name_only}" ]; then
		echo "PRESENT: '${file}'"
	else
		ln -s "${DIR}/home/${name_only}" "$HOME/${name_only}"
		echo "CREATED: ${file}'"
	fi
}

# Link all files in home/
DOTTHINGS=$(find home -maxdepth 1 -type f -name ".*" -not -name "*DS_Store*")
for f in ${DOTTHINGS}; do
	link_or_fail "$f"
done

link_or_fail "home/.zsh"
link_or_fail "biome.json"
link_or_fail "home/.hammerspoon"
link_or_fail "selene.toml"

for f in home/.config/*; do
	link_or_fail "$f"
done

# Opencode
for file in opencode.jsonc tui.json AGENTS.md; do
	target="$HOME/.config/opencode/$file"
	source="${DIR}/home/.config/opencode/$file"

	if [[ ! -e "$target" ]]; then
		ln -s "$source" "$target"
		echo "CREATED: '${target}'"
	else
		echo "PRESENT: '${target}'"
	fi
done

exit 0
