#!/bin/bash

curl -s -L "https://raw.githubusercontent.com/sindresorhus/pure/master/async.zsh" -o home/.zsh/modules/pure_prompt/async.zsh
curl -s -L "https://iterm2.com/shell_integration/zsh" -o ./home/.zsh/config/iterm2-integration.sh
curl -s -L "https://gitlab.com/openconnect/vpnc-scripts/-/raw/master/vpnc-script" -o ./home/extras/vpnc-script && chmod +x ./home/extras/vpnc-script 

if [[ ! -e "$HOME/.zsh/modules/fzf-tab" ]]; then
  git clone https://github.com/Aloxaf/fzf-tab ~/.zsh/modules/fzf-tab
else
  (cd ~/.zsh/modules/fzf-tab && git pull --rebase)
fi

pushd "$HOME/.zsh/modules/fzf-tab/modules" || exit 1
CPPFLAGS=-I/$HOMEBREW_PREFIX/include CFLAGS="-g -Wall -O2" LDFLAGS=-L$HOMEBREW_PREFIX/lib ./configure --disable-gdbm --without-tcsetpgrp DL_EXT=bundle
make -j
popd || exit 0
