#!/bin/bash
#
# Updates all included submodules to the recent COMMIT
# See http://stackoverflow.com/questions/1030169/git-easy-way-pull-latest-of-all-submodules
# and ... http://woss.name/2008/04/09/using-git-submodules-to-track-plugins/
#
# Short version:
# Unlike svn:externals "git submodule" adds a submodule AT A SPECIFIC commit. There's no auto-update!
#

# First update all submodules to HEAD
git submodule foreach git pull origin master

# Then add changes to superproject
git add home/.zsh/modules

# Commit
git commit -m "Updated submodules to the newest version"

# Push upstream
git push
