#!/bin/sh
#
# Loads a session/profile named "tig" in iTerm
#
# create a profile named "tig" and set "send text on start" to "ti && exit 0" for a nice big tig window
#
osascript 2>/dev/null <<EOF
tell application "iTerm"
	set newWindow to (create window with profile "tig")
	tell newWindow
		tell current session
			set columns to 200
			set rows to 200
		end tell
	end tell
end tell
EOF
exit 0

# vim:ft=sh
