#!/bin/bash
# in .subversion/config: diff-cmd = /path/to/vimsvndiff_wrapper

# Configure your favorite diff program here.
DIFF="/opt/local/bin/mvim -d"

# Subversion provides the paths we need as the sixth and seventh
# parameters.
LEFT=${6}
RIGHT=${7}

# Call the diff command (change the following line to make sense for
# your merge program).
$DIFF $LEFT $RIGHT

