gui:
  scrollHeight: 2
  language: "en"
  timeFormat: "02.01" # https://gosamples.dev/date-time-format-cheatsheet/
  shortTimeFormat: "15:04"
  nerdFontsVersion: "3"
git:
  skipHookPrefix: "[FORCE]"
os:
  edit: "PATH=/opt/homebrew/bin/:$PATH; vim -N -u ~/.vimrc --cmd 'let g:vim_commandline=1' -c 'normal A' -c 'startinsert' -- {{filename}}"
  editAtLine: "PATH=/opt/homebrew/bin/:$PATH; vim -N -u ~/.vimrc --cmd 'let g:vim_commandline=1' -c 'normal A' -c 'startinsert' +{{line}} -- {{filename}}"
  editAtLineAndWait: "PATH=/opt/homebrew/bin/:$PATH; vim -N -u ~/.vimrc --cmd 'let g:vim_commandline=1' -c 'normal A' --block -c 'startinsert' +{{line}} -- {{filename}}"
  editInTerminal: true
