#!/bin/bash
#
# Generate tags for all installed gems
#
GEM_DIR=`gem env | grep "INSTALLATION DIRECTORY" | cut -d ":" -f 2 | sed "s/ //g" | head -n 1`/gems
TAGS_FILE="tags"

echo "Generating missing tags for all gems in $GEM_DIR"
cd $GEM_DIR

for gem in *; do
  if [ -d "$GEM_DIR/$gem" ]; then
    cd "$GEM_DIR/$gem"
    if [ ! -f "$TAGS_FILE" ]; then
      echo "$gem : generated"
      rtags -R -f $TAGS_FILE
    fi
    cd ..
  fi
done
