#!/bin/bash
#
# Generate tags for all installed gems
#
GEM_DIR=`gem env | grep "INSTALLATION DIRECTORY" | cut -d ":" -f 2 | sed "s/ //g"`/gems
TAGS_FILE=".tags"

echo "Generating missing tags for all gems in $GEM_DIR"
cd $GEM_DIR

for gem in *; do
  cd $gem
  if [ ! -f "$TAGS_FILE" ]; then
    echo "$gem : generated"
    `ctags -R --languages=ruby -u -f $TAGS_FILE`
  else
    `head -n 2 $TAGS_FILE | grep -q "TAG_FILE_SORTED[[:space:]]\.*0"`
    if [ "$?" -ne "0" ]; then
      echo "$gem : fixed (was sorted)"
      `ctags -R --languages=ruby -u -f $TAGS_FILE`
    fi
  fi
  cd ..
done
