[env]
default_config_filename = "mise.toml"
_.path = "{{ cwd }}/node_modules/.bin"

[tools]
"github:boyter/cs" = "latest"
"github:psanford/wormhole-william" = { version = "latest", bin = "wormhole" }
"cargo:your-tools/ruplacer" = "latest"  # Now on codeberg without releases for macos

[settings]
experimental = true
python.uv_venv_auto = true

[settings.ruby]
compile = false
