#!/bin/bash
# Backup of all installed packages into single adb restore capable files
#
declare -a PACKAGES

IFS=$'\n' PACKAGES=($(adb shell 'pm list packages -f' | sed -e 's/.*=//' | grep -v "com.android" | grep -v "com.google.android" | grep -v "com.qualcomm" | grep -v "org.cyanogenmod." | grep -v "android" | sort))
echo "Found ${#PACKAGES[*]} packages"

folder=$(date +%Y%m%d-%H%m)
mkdir "${folder}"

for pack in ${PACKAGES[@]}; do
  if [[ "${pack}" =~ \. ]]; then
    echo "Saving ${pack} to ${pack}.adb-backup"
    adb backup -f "${folder}/${pack}.adb-backup" -apk -obb "${pack}" &
    sleep 2
    adb shell input touchscreen tap 1001 2456
    wait $(jobs -p)
  fi
done
