#!/bin/sh

# p4merge
#/Applications/p4merge.app/Contents/MacOS/p4merge $*

# Araxis merge
#/Applications/Araxis\ Merge.app/Contents/Utilities/compare \
#     -max \
#     --title1:"Theirs=${theirs##*/}" \
#     --title2:"Mine=${mine##*/}" \
#     --title3:"Result=${merged##*/}" \
#     "$theirs" "$mine" "$merged" 
 
base=${1?1st argument is 'base' file}
theirs=${2?2nd argument is 'theirs' file}
mine=${3?3rd argument is 'mine' file}
merged=${4?4th argument is 'merged' file}

# MELD:
cat "$mine" > "$merged"
meld --auto-merge --auto-compare --label="Base=${base##*/}"           "$base"   \
     --label="Mine->Merged=${merged##*/}" "$merged" \
     --label="Theirs=${theirs##*/}"       "$theirs"

