#!/bin/sh
# Calls p4merge for use with "git mergetool"

# p4merge
#/Applications/p4merge.app/Contents/MacOS/p4merge $*

# meld
base=${1?1st argument is 'base' file}
theirs=${2?2nd argument is 'theirs' file}
mine=${3?3rd argument is 'mine' file}
merged=${4?4th argument is 'merged' file}

cat "$mine" > "$merged"
meld --label="Base=${base##*/}"           "$base"   \
     --label="Mine->Merged=${merged##*/}" "$merged" \
     --label="Theirs=${theirs##*/}"       "$theirs"
