-- === ClipboardTool ===
--
-- Keep a history of the clipboard for text entries and manage the entries with a context menu
--
local obj = {}
obj.__index = obj

-- Metadata
obj.name = "ClipboardToolSqlite"
obj.version = "0.8"
obj.author = "Alfred Schilken <alfred@schilken.de>"
obj.homepage = "https://github.com/Hammerspoon/Spoons"
obj.license = "MIT - https://opensource.org/licenses/MIT"

local isImage = function(object)
  if object == nil then
    return false
  end
  local mt = getmetatable(object)
  return mt ~= nil and mt.saveToFile ~= nil
end

--- ClipboardTool.frequency
--- Variable
--- Speed in seconds to check for clipboard changes. If you check too frequently, you will degrade performance, if you check sparsely you will loose copies. Defaults to 0.8.
obj.frequency = 0.8

--- ClipboardTool.hist_size
--- Variable
--- How many items to keep on history.
obj.hist_size = 100

--- ClipboardTool.honor_ignoredidentifiers
--- Variable
--- If `true`, check the data identifiers set in the pasteboard and ignore entries which match those listed in `ClipboardTool.ignoredIdentifiers`. The list of identifiers comes from http://nspasteboard.org. Defaults to `true`
obj.honor_ignoredidentifiers = true

--- ClipboardTool.ignoredIdentifiers
--- Variable
--- Types of clipboard entries to ignore, see http://nspasteboard.org. Code from https://github.com/asmagill/hammerspoon-config/blob/master/utils/_menus/newClipper.lua. Default value (don't modify unless you know what you are doing):
--- ```
---  {
---     ["de.petermaurer.TransientPasteboardType"] = true, -- Transient : Textpander, TextExpander, Butler
---     ["com.typeit4me.clipping"]                 = true, -- Transient : TypeIt4Me
---     ["Pasteboard generator type"]              = true, -- Transient : Typinator
---     ["com.agilebits.onepassword"]              = true, -- Confidential : 1Password
---     ["org.nspasteboard.TransientType"]         = true, -- Universal, Transient
---     ["org.nspasteboard.ConcealedType"]         = true, -- Universal, Concealed
---     ["org.nspasteboard.AutoGeneratedType"]     = true, -- Universal, Automatic
---  }
--- ```
obj.ignoredIdentifiers = {
  ["de.petermaurer.TransientPasteboardType"] = true, -- Transient : Textpander, TextExpander, Butler
  ["com.typeit4me.clipping"] = true, -- Transient : TypeIt4Me
  ["Pasteboard generator type"] = true, -- Transient : Typinator
  ["com.agilebits.onepassword"] = true, -- Confidential : 1Password
  ["org.nspasteboard.TransientType"] = true, -- Universal, Transient
  ["org.nspasteboard.ConcealedType"] = true, -- Universal, Concealed
  ["org.nspasteboard.AutoGeneratedType"] = true, -- Universal, Automatic
}

--- ClipboardTool.deduplicate
--- Variable
--- Whether to remove duplicates from the list, keeping only the latest one. Defaults to `true`.
obj.deduplicate = true

-- Maximum size of paste entry to display
obj.maxSizeEntryDisplay = 200

----------------------------------------------------------------------

-- Internal variable - Chooser/menu object
obj.selectorobj = nil

-- Internal variable - Cache for focused window to work around the current window losing focus after the chooser comes up
obj.prevFocusedWindow = nil

-- Internal variable - Timer objects to look for pasteboard changes and trim the DB
obj.timer = nil
obj.timer_store_cleanup = nil

-- DATASTORE for pasteboard history
obj.store = nil
obj.sqlite_insert_stmt = nil

local pasteboard = require("hs.pasteboard") -- http://www.hammerspoon.org/docs/hs.pasteboard.html
local hashfn = require("hs.hash").MD5
local sqlite = require("hs.sqlite3")

-- Keep track of last change counter
local last_change = nil
-- In-memory display cache (populated from SQLite on start)
local clipboard_history = nil

local styledTextAttribs = {
  paragraphStyle = { maximumLineHeight = 15 },
  font = { name = "InconsolataGo Nerd Font", size = 14 },
  color = hs.drawing.color.definedCollections.hammerspoon.black,
}

local function makeStyledText(s)
  return hs.styledtext.new(s, styledTextAttribs)
end

-- Internal function - build a display-cache entry from a SQLite row
local function rowToHistoryEntry(row, maxSize)
  local display = row.content
  if row.type ~= "image" and #display > maxSize then
    display = string.sub(display, 1, maxSize) .. "... \n[+" .. (#display - maxSize) .. " bytes more]"
  end
  return {
    content = display,
    id = row.id,
    type = row.type,
    subText = row.sub_text,
    styledText = makeStyledText(display),
  }
end

-- Internal method - process the selected item from the chooser.
function obj:pasteSelectedItem(value)
  if value == nil then
    return
  end

  if self.prevFocusedWindow ~= nil then
    self.prevFocusedWindow:focus()
  end

  local stmt = self.store:prepare("SELECT content, type FROM pasteboard WHERE id = ?")
  stmt:bind_values(value.storeId)
  local result = stmt:step()

  if result ~= hs.sqlite3.DONE and result ~= hs.sqlite3.ROW then
    print("ClipboardToolSqlite error: " .. self.store:error_message())
    stmt:finalize()
    return
  end

  local row = nil
  local success, r = pcall(function()
    row = stmt:get_named_values()
  end)
  stmt:reset()
  stmt:finalize()

  if not success then
    print("[ClipboardToolSqlite] Error: " .. r)
    return
  end

  last_change = pasteboard.changeCount()

  if row.type == "image" then
    pasteboard.writeObjects(hs.image.imageFromURL(row.content))
  else
    pasteboard.setContents(row.content)
  end

  -- Plain paste; JSON/iTerm2 formatting removed
  hs.eventtap.keyStroke({ "cmd" }, "v")
end

-- Internal method: deduplicate the given list, and restrict it to the history size limit
function obj:dedupe_and_resize(list)
  local res = {}
  local hashes = {}
  for _, v in ipairs(list) do
    if #res < self.hist_size and v.content ~= nil then
      local hash = hashfn(v.content)
      if (not self.deduplicate) or not hashes[hash] then
        table.insert(res, v)
        hashes[hash] = true
      end
    end
  end
  return res
end

function obj:cleanup_store_handler()
  local stmt =
    self.store:prepare("DELETE FROM pasteboard WHERE id NOT IN (SELECT id FROM pasteboard ORDER BY id DESC LIMIT ?)")
  stmt:bind_values(self.hist_size)
  stmt:step()
  stmt:finalize()
end

--- ClipboardTool:pasteboardToClipboard(item)
--- Method
--- Add the given string to the history
---
--- Parameters:
---  * item - string or image to add to the clipboard history
---
--- Returns:
---  * None
function obj:pasteboardToClipboard(item)
  local display = item
  local type = "string"
  local sub_text = nil

  -- Image?
  if isImage(item) then
    local size = item:size()
    type = "image"
    display = item:size({ ["h"] = 100, ["w"] = 250 }):encodeAsURLString()
    item = item:encodeAsURLString()
    sub_text = "Image: " .. math.floor(size.w) .. " x " .. math.floor(size.h) .. " px"
  end

  if type == "string" and #item > self.maxSizeEntryDisplay then
    display = string.sub(item, 1, self.maxSizeEntryDisplay)
      .. "... \n[+"
      .. (#item - self.maxSizeEntryDisplay)
      .. " bytes more]"
  end

  self.sqlite_insert_stmt:bind_values(type, item, sub_text)
  self.sqlite_insert_stmt:step()
  self.sqlite_insert_stmt:reset()
  local storeId = self.store:last_insert_rowid()

  local entry = {
    content = display,
    id = storeId,
    type = type,
    subText = sub_text,
    styledText = makeStyledText(display),
  }

  table.insert(clipboard_history, 1, entry)
  clipboard_history = self:dedupe_and_resize(clipboard_history)
end

-- Internal function - fill in the chooser options
function obj._populateChooser(_self)
  local menuData = {}

  for _, v in ipairs(clipboard_history) do
    local chooser_item = {
      text = v.styledText or makeStyledText(v.content),
      subText = v.type ~= "string" and v.type or nil,
      storeId = v.id,
    }

    if v.type == "image" then
      chooser_item.subText = nil
      chooser_item.text = v.subText
      chooser_item.image = hs.image.imageFromURL(v.content)
    end

    table.insert(menuData, chooser_item)
  end
  return menuData
end

--- ClipboardTool:shouldBeStored()
--- Method
--- Verify whether the pasteboard contents matches one of the values in `ClipboardTool.ignoredIdentifiers`
function obj:shouldBeStored()
  -- Code from https://github.com/asmagill/hammerspoon-config/blob/master/utils/_menus/newClipper.lua
  local goAhead = true
  for _, v in ipairs(hs.pasteboard.pasteboardTypes()) do
    if self.ignoredIdentifiers[v] then
      goAhead = false
      break
    end
  end
  if goAhead then
    for _, v in ipairs(hs.pasteboard.contentTypes()) do
      if self.ignoredIdentifiers[v] then
        goAhead = false
        break
      end
    end
  end
  return goAhead
end

--- ClipboardTool:checkAndStorePasteboard()
--- Method
--- If the pasteboard has changed, we add the current item to our history and update the counter
function obj:checkAndStorePasteboard()
  local now = pasteboard.changeCount()
  if now > last_change then
    if (not self.honor_ignoredidentifiers) or self:shouldBeStored() then
      local current_clipboard = pasteboard.readImage() or pasteboard.getContents()

      -- Do not add whitespace-only content
      if current_clipboard ~= nil then
        if isImage(current_clipboard) or (string.match(current_clipboard, "^%s+$") == nil) then
          self:pasteboardToClipboard(current_clipboard)
        end
      end
    end
    last_change = now
  end
end

--- ClipboardTool:start()
--- Method
--- Start the clipboard history collector
function obj:start()
  self.store = sqlite.open(hs.configdir .. "/ClipboardToolSqlite.sqlite3")
  self.store:exec([[
    CREATE TABLE IF NOT EXISTS pasteboard (
      id       INTEGER PRIMARY KEY AUTOINCREMENT,
      type     TEXT NOT NULL,
      content  BLOB NOT NULL,
      sub_text TEXT
    );
    CREATE INDEX IF NOT EXISTS idx_pasteboard_id ON pasteboard(id);
  ]])
  self.sqlite_insert_stmt = self.store:prepare([[INSERT INTO pasteboard(type, content, sub_text) VALUES(?, ?, ?);]])

  clipboard_history = {}
  for row in
    self.store:nrows(
      string.format("SELECT id, type, content, sub_text FROM pasteboard ORDER BY id DESC LIMIT %d", self.hist_size)
    )
  do
    table.insert(clipboard_history, rowToHistoryEntry(row, self.maxSizeEntryDisplay))
  end
  clipboard_history = self:dedupe_and_resize(clipboard_history)

  last_change = pasteboard.changeCount()

  -- Build the chooser
  self.selectorobj = hs.chooser.new(hs.fnutils.partial(self.pasteSelectedItem, self))
  self.selectorobj:choices(hs.fnutils.partial(self._populateChooser, self))

  -- Checks for changes on the pasteboard
  self.timer = hs.timer.new(self.frequency, hs.fnutils.partial(self.checkAndStorePasteboard, self))
  self.timer:start()

  -- Trim the database every 2 minutes
  self.timer_store_cleanup = hs.timer.new(120, hs.fnutils.partial(self.cleanup_store_handler, self))
  self.timer_store_cleanup:start()
end

--- ClipboardTool:stop()
--- Method
--- Stop the clipboard history collector and release all resources
function obj:stop()
  if self.timer then
    self.timer:stop()
  end
  if self.timer_store_cleanup then
    self.timer_store_cleanup:stop()
  end
  if self.sqlite_insert_stmt then
    self.sqlite_insert_stmt:finalize()
  end
  if self.store then
    self.store:close()
  end
  self.selectorobj = nil
end

--- ClipboardTool:showClipboard()
--- Method
--- Display the current clipboard list in a chooser
function obj:showClipboard()
  if self.selectorobj ~= nil then
    self.selectorobj:refreshChoicesCallback()
    self.prevFocusedWindow = hs.window.focusedWindow()
    self.selectorobj:show()
  else
    hs.notify.show("ClipboardTool not properly initialized", "Did you call ClipboardToolSqlite:start()?", "")
  end
end

--- ClipboardTool:bindHotkeys(mapping)
--- Method
--- Binds hotkeys for ClipboardTool
---
--- Parameters:
---  * mapping - A table containing hotkey obj/key details for the following items:
function obj:bindHotkeys(mapping)
  local def = {
    show_clipboard = hs.fnutils.partial(self.showClipboard, self),
  }
  hs.spoons.bindHotkeysToSpec(def, mapping)
  obj.mapping = mapping
end

return obj
