#!/usr/bin/env bash
#
# Regenerates prefpane_translations.lua from prefpane_translations.conf.
#
# prefpane_translations.conf is the human-edited source of truth (simple
# BundleName=German Name pairs). This script converts it into a Lua table
# that seal_appsfzy.lua loads at runtime, and also scans the real
# PreferencePanes search paths on this machine to warn about any installed
# .prefPane bundle that doesn't have a translation yet (it will just fall
# back to its English name until one is added).
#
# Usage: ./prefpane_translations.sh

set -euo pipefail

spoon_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
conf_file="$spoon_dir/prefpane_translations.conf"
lua_file="$spoon_dir/prefpane_translations.lua"

if [[ ! -f "$conf_file" ]]; then
  echo "ERROR: translation source file not found: $conf_file" >&2
  exit 1
fi

# Directories Seal's appsfzy plugin searches for .prefPane bundles.
search_paths=(
  "/System/Library/PreferencePanes"
  "/Library/PreferencePanes"
  "$HOME/Library/PreferencePanes"
)

declare -A translations
keys=()

while IFS= read -r line || [[ -n "$line" ]]; do
  # Strip comments and surrounding whitespace
  line="${line%%#*}"
  line="$(echo -n "$line" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
  [[ -z "$line" ]] && continue

  key="${line%%=*}"
  value="${line#*=}"
  [[ -z "$key" ]] && continue

  translations["$key"]="$value"
  keys+=("$key")
done < "$conf_file"

if [[ ${#keys[@]} -eq 0 ]]; then
  echo "ERROR: no translations found in $conf_file" >&2
  exit 1
fi

# Warn about installed prefPanes that have no translation entry.
for dir in "${search_paths[@]}"; do
  [[ -d "$dir" ]] || continue
  while IFS= read -r -d '' bundle; do
    name="$(basename "$bundle" .prefPane)"
    if [[ -z "${translations[$name]+set}" ]]; then
      echo "WARN: no translation for \"$name\" ($bundle) — falling back to English name" >&2
    fi
  done < <(find "$dir" -maxdepth 1 -iname "*.prefPane" -print0 2>/dev/null)
done

# Sort keys for deterministic output.
IFS=$'\n' sorted_keys=($(sort <<<"${keys[*]}"))
unset IFS

{
  echo "-- AUTO-GENERATED by prefpane_translations.sh"
  echo "-- Do not edit by hand — edit prefpane_translations.conf instead."
  echo "return {"
  for key in "${sorted_keys[@]}"; do
    value="${translations[$key]}"
    # Escape backslashes and double quotes for Lua string literals.
    escaped_value="${value//\\/\\\\}"
    escaped_value="${escaped_value//\"/\\\"}"
    escaped_key="${key//\\/\\\\}"
    escaped_key="${escaped_key//\"/\\\"}"
    echo "  [\"$escaped_key\"] = \"$escaped_value\","
  done
  echo "}"
} > "$lua_file"

echo "Wrote $(basename "$lua_file") with ${#sorted_keys[@]} translations." >&2
