#!/bin/bash
#
# Converts a video to mobile phone compatible
#
for file in "$@"; do
  video_format=$(ffmpeg -i "$file" 2>&1 | grep "Video: h264")

  current_size=$(ffmpeg -i "$file" 2>&1 | grep Video: | grep -o ' [0-9]\+x[0-9]\+[ ,]' | tr ',' ' ')
  audio_streams=$(ffmpeg -i "$file" 2>&1 | grep "Stream #.* Audio")

  width=$(echo $current_size | cut -d "x" -f 1)
  height=$(echo $current_size | cut -d "x" -f 2)

  echo "Source video size is $width x $height px"

  # Note : 1080 x 1920 
  if [[ "$width" -gt 1920 || "$height" -gt 1080 ]]; then
    height=1080
    width=1920
  fi

  target=$width"x"$height
  filename=$(basename "$file")
  extension="${filename##*.}"
  filename="${filename%.*}"

  [ -e "${filename}.mp4" ] && filename="${filename}.${RANDOM}"

  echo "Target video size is $target px"
  echo "Extension: ${extension}"

  if [[ "$video_format" == "" || "${FORCE}" == "1" ]]; then
    # Not a mp4 video steam inside
    ffmpeg -i "$file" -movflags +faststart -strict experimental -y -f mp4 -vcodec libx264 -preset slow -crf 22 -acodec libmp3lame -ab 160000 -ac 2 -s $target "${filename}.mp4"
  else
    # mp4 inside container
    ffmpeg -i "$file" -vcodec copy -acodec copy "${filename}.mp4"
  fi

  echo "Saved to ${filename}.mp4"
done
